// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwuaatgjrblhyzvkcmea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3dWFhdGdqcmJsaHl6dmtjbWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzcyMDUsImV4cCI6MjA3MTExMzIwNX0.swlddmQ9iVdyM3ff3tZY4xF7lNrePywdC6tST-Hsdb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});